export enum OrderStatus {
  AWAITING_SUBMIT = 'AWAITING_SUBMIT',
  AWAITING_DEPOSIT_1 = 'AWAITING_DEPOSIT_1',
  AWAITING_CAPTURE = 'AWAITING_CAPTURE',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  AWAITING_DEPOSIT = 'AWAITING_DEPOSIT',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  IN_PRODUCTION = 'IN_PRODUCTION',
  AWAITING_REMAINING = 'AWAITING_REMAINING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
