export enum WarrantyClaimStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PENDING_RECEIVE = 'PENDING_RECEIVE',
  IN_SERVICE = 'IN_SERVICE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
